version: '2.1'

services:
  mongo:
   image: mongo
   ports:
     — “27017:27017”
  web:
    build: .
    command: bash -c "mocha"
    environment:
    mongodb://admin:admin@127.0.0.1:27017/dbname
      - DATABASE_URL=mongo://admin:admin@postgres:5432/dbname
      - NODE_ENV=test
    depends_on:
      mongo:
        condition: service_healthy
    links:
     - mongo
