// Generated by CoffeeScript 1.5.0
(function() {
  var conf, confs, env;

  confs = {
    "development": {
      "db": 'mongodb://' + process.env.MONGO_PORT_27017_TCP_ADDR + ':27017/myapp-dev'
    },
    "testing": {
      "db": 'mongodb://' + process.env.MONGO_PORT_27017_TCP_ADDR + ':27017/myapp-test'
    }
  };

  env = process.env.NODE_ENV;

  if (!env) {
    process.env.NODE_ENV = "development";
  }

  conf = confs[env];

  if (!conf) {
    conf = confs["development"];
  }

  module.exports = conf;

}).call(this);
